export const GET_TAG_FILTERED_BOOTCAMPS = 'GET_TAG_FILTERED_BOOTCAMPS';
export const GET_BOOTCAMPS_ERROR = 'GET_BOOTCAMPS_ERROR';
export const GET_TAG_FILTERED_COURSES = 'GET_TAG_FILTERED_COURSES';
export const GET_COURSES_ERROR = 'GET_COURSES_ERROR';
